# Generated by Django 3.2.12 on 2025-12-12 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_remove_product_qty_remove_supply_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-date'], 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AddField(
            model_name='supply',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
